openapi: 3.0.0
info:
  title: Movie Finder API
  version: 1.0.0
paths:
  /api/movies:
    get:
      summary: Obtiene todas las películas
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                - id: 1
                  title: "Pelicula 1"
                - id: 2
                  title: "Pelicula 2"
                # ... otras películas ...

  /api/movies/{id}:
    get:
      summary: Obtiene los detalles de una película por ID
      parameters:
        - name: id
          in: path
          description: ID de la película a obtener
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                id: 1
                title: "Pelicula 1"
                overview: "Descripción de la película 1"
                release_date: "2022-01-01"

  /api/movies/movies/{title}:
    get:
      summary: Busca películas por titulo
      parameters:
        - name: title
          in: path
          description: Texto de búsqueda para el título de la película
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                id: 1
                title: "Pelicula 1"
                overview: "Descripción de la película 1"
                release_date: "2022-01-01"


  /api/movies/search/title:
    get:
      summary: Busca películas por nombre
      parameters:
        - name: query
          in: query
          description: Texto de búsqueda
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Éxito
          content:
            application/json:
              example:
                - id: 1
                  title: "Pelicula 1"
                - id: 2
                  title: "Pelicula 2"
                # ... otras películas ...
